### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [Gautamshahi/FakeCovid#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/WPZAVK
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by Gautamshahi** [comment]
Hello,

Thank you for adding the data to CoronaWhy.

I really appreciate your effort. What can do to update the metadata?

I have updated the data, so will it be possible to update the data in your portal CoronaWhy?
